version: '2.1'

services:
  hello-service:
    build: ./hello-service
    mem_limit: 350m
    image: hands-on/hello-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
    links:
      - eureka:eureka
  hello-service-consumer:
    build: ./hello-service-consumer
    mem_limit: 350m
    image: hands-on/hello-service-consumer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
    links:
      - eureka:eureka
  eureka:
    build: ./eureka-server
    mem_limit: 350m
    image: hands-on/eureka

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: ./hello-service-gateway
    mem_limit: 350m
    image: hands-on/gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    links:
      - eureka:eureka
  
