spring:
  application:
    name: hello-service-ribbon
server:
  port: 8080
  
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  http:
    client:
      enabled: true

backend:
  ribbon:
    eureka:
      enabled: false
    client:
      enabled: true
    ServerListRefreshInterval: 5000

hystrix.command.BackendCall.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.threadpool.BackendCallThread.coreSize: 5

