apiVersion: v1
kind: Service
metadata:
  name: hello-service-consumer
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 31003
      port: 8080
      targetPort: 8080
    - name: management
      nodePort: 31004
      port: 8081
      targetPort: 8081
  selector:
    app: hello-service-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service-consumer
  labels:
    app: hello-service-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service-consumer
  template:
    metadata:
      name: hello-service-consumer
      labels:
        app: hello-service-consumer
    spec:
      restartPolicy: Always
      containers:
        - name: hello-service-consumer
          image: hands-on/hello-service-consumer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management
          resources:
            limits:
              memory: 1000Mi
              cpu: 1000m
            requests:
              memory: 500Mi
              cpu: 500m