apiVersion: v1
kind: Service
metadata:
  name: hello-service-ribbon
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 31005
      port: 8080
      targetPort: 8080
    - name: management
      nodePort: 31006
      port: 8081
      targetPort: 8081
  selector:
    app: hello-service-ribbon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service-ribbon
  labels:
    app: hello-service-ribbon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service-ribbon
  template:
    metadata:
      name: hello-service-ribbon
      labels:
        app: hello-service-ribbon
    spec:
      restartPolicy: Always
      containers:
        - name: hello-service-ribbon
          image: hands-on/hello-service-ribbon
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management
          resources:
            limits:
              memory: 1000Mi
              cpu: 1000m
            requests:
              memory: 500Mi
              cpu: 500m