spring:
  application:
    name: hello-service-consumer
    
server:
  port: 8080
  
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
        
feign:
  hystrix:
    enabled: true